### ISSUE TITLE
Fix body alignment with header and footer elements

### ISSUE THREAD

**Issue by AntonioP22** [AntonioP22/frontendiscord#2]
Body sizing is overlapping with the header and footer elements.

**Comment by lodenrogue** [comment]
I see you added the good first issue tag on this. Can you add some README build and run instructions so I can help with this issue?

**Comment by AntonioP22** [comment]
I’ll add some read me info as I know it’s blank but could you clarify what are run instructions?

**Comment by lodenrogue** [comment]
How to build and run the application. How can I get the code running on my computer?

**Comment by AntonioP22** [comment]
Ah okay sorry and you should be able to fork the repo onto your desktop or somewhere and open it up in your editor. I don’t believe there should be anything extra to get it going
